package ch4_language_java;

/*
class ChainExcDemo {
    static void demoproc {
        NullPointerException е = new NullPointerException("верхний уровень");
        е.initCause(new ArithmeticException("причина"));
        throw е;
    }
    public static void main(String args[]) {
        try {
            demoproc();
        }
        catch(NullPointerException e) {
            System.out.println("Перехвачено: " + е) ;
            System.out.println("Исходная причина: " + е. getCause О) ;
        }
    }
}
*/

